---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.io/scm-tag: HEAD
    jkube.io/scm-url: https://github.com/spring-cloud/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
  labels:
    app: kubernetes-hello-world
    provider: jkube
    version: 3.0.0-SNAPSHOT
    group: org.springframework.cloud
  name: kubernetes-hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kubernetes-hello-world
      provider: jkube
      group: org.springframework.cloud
  template:
    metadata:
      annotations:
        jkube.io/scm-tag: HEAD
        jkube.io/scm-url: https://github.com/spring-cloud/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
      labels:
        app: kubernetes-hello-world
        provider: jkube
        version: 3.0.0-SNAPSHOT
        group: org.springframework.cloud
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: cloud/kubernetes-hello-world:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
